# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
	- oldrel
sudo: false

warnings_are_errors: false

addons:
  apt:
    packages:
      - gdal-bin
      - proj-bin
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev
      - r-cran-ncdf4
      - r-cran-rgl
      - libv8-3.14-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libudunits2-dev
      - libnetcdf-dev
      - libjq-dev
      - libcgal-dev
      - libglu1-mesa-dev

#before_install:
#  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
