# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false

warnings_are_errors: false

before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

packages:
  - libproj-dev
  - libgeos-dev
  - libspatialite-dev
  - libgdal-dev
