# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false

before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:cran/jq --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev libpoppler-cpp-dev
  - sudo apt-get install -y gdal-bin
  - sudo apt-get install -y aria2
  - PATH="/usr/local/gdal/bin:$PATH"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

apt_packages:
    - libgdal-dev
    - libproj-dev
    - libcairo2-dev
    - libatk1.0-dev
    - libpango1.0-dev
    - libgtk2.0-dev
    - libglib2.0-dev
    - libcurl4-openssl-dev
    - libudunits2-dev
